import "./tokens.css";
import "./site.css";
import "./setup";
import { mountChart } from "./chart";
import { mountDock, mountSoundToggle } from "./dock";
import { mountEffects } from "./fx";
import { preloadMotion } from "./motion";
import { mountShareControl, mountShareNote } from "./share";
import { mountHome } from "./sim";
import { mountSound } from "./sound";
import { mountThresholds } from "./thresholds";

mountSound();
mountSoundToggle();
mountDock();
mountChart();
mountThresholds();
mountHome();
mountEffects();
preloadMotion();
mountShareNote();
mountShareControl();
